### ISSUE TITLE
Hello 为什么这个仓库是空的？

### ISSUE THREAD

**Issue by cnkjw** [Scicomath/glauber#1]
Hello 艾鑫！

**Comment by Scicomath** [comment]
哈哈，这些都是研究生的时候弄的，早就没弄这方面的东西了。。。

**Comment by cnkjw** [comment]
大佬你的 [http://Scicomath.github.io](http://Scicomath.github.io) 被重定向到广告网页了。

**Comment by Scicomath** [comment]
> 大佬你的 http://Scicomath.github.io 被重定向到广告网页了。

域名很早就没有续费了... (⊙﹏⊙)b
Scicomath.github.io项目我现在已经关了...
